name: Type Checking

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/type-checking.yml"
      - "setup.cfg"
      - "pyproject.toml"
      - "requirements.txt"
      - "**/*.py"

jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      # mypy is os and python-version sensitive. Test on all supported combinations
      matrix:
        # Arm runners are faster (as long as the same wheels are available)
        os: [windows-11-arm, ubuntu-24.04-arm, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        # actions/setup-python doesn't support Python < 3.11 on ARM
        exclude:
          - python-version: "3.9"
            os: windows-11-arm
          - python-version: "3.10"
            os: windows-11-arm
        include:
          - python-version: "3.9"
            os: windows-latest
          - python-version: "3.10"
            os: windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -r "requirements.txt"
      - run: mypy . --python-version=${{ matrix.python-version }}
